#!/usr/bin/env php

<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use Illuminate\Filesystem\Filesystem;
use JonathanTorres\Construct\Commands\ConstructCommand;
use JonathanTorres\Construct\Construct;
use JonathanTorres\Construct\Helpers\Str;
use Symfony\Component\Console\Application;

$app = new Application('Construct', '1.3.0');
$construct = new Construct(new Filesystem(), new Str());
$app->add(new ConstructCommand($construct, new Str()));
$app->run();
