#!/usr/bin/env php

<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use JonathanTorres\Construct\Commands\ConstructCommand;
use JonathanTorres\Construct\Commands\InteractiveCommand;
use JonathanTorres\Construct\Construct;
use JonathanTorres\Construct\Helpers\Filesystem;
use JonathanTorres\Construct\Helpers\Str;
use Symfony\Component\Console\Application;

$str = new Str();
$filesystem = new Filesystem();
$construct = new Construct($filesystem, $str);
$app = new Application('Construct', '1.9.0');
$app->add(new ConstructCommand($construct, $str, $filesystem));
$app->add(new InteractiveCommand($construct, $str));
$app->run();
